# Generated by Django 5.2.15 on 2026-07-06 13:51

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('fb_handle', models.CharField(max_length=255)),
                ('insta_handle', models.CharField(max_length=255)),
                ('youtube_handle', models.CharField(max_length=255)),
                ('twitter_handle', models.CharField(max_length=255)),
                ('description_1', ckeditor.fields.RichTextField(blank=True)),
                ('description_2', ckeditor.fields.RichTextField(blank=True)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
